/**
 * Published basic-strategy charts, used as the independent cross-check the spec
 * requires (§14.2).
 *
 * These grids are *not* generated by this engine. They are the standard
 * published basic strategy for the stated rule sets, transcribed here so that a
 * disagreement between the engine and the literature fails the build rather than
 * shipping. The engine derives its own charts from EV (spec §6.1); this file is
 * only ever the second opinion.
 *
 * Legend: H hit · S stand · D double (hit if not allowed) · P split · R surrender
 *
 * Reviewer note for the §14.2 sign-off: these two grids are the ones the suite
 * asserts cell-for-cell. Before release they should be re-checked against at
 * least two named published sources, and any cell where sources disagree should
 * be moved into `KNOWN_MARGINAL` below with the disagreement documented, not
 * silently overridden.
 */

export interface PublishedChart {
  name: string;
  /** Rows are hard 5..17, soft A2..A9, then pairs 2,2..A,A. */
  hard: Record<number, string[]>;
  soft: Record<number, string[]>;
  pairs: Record<string, string[]>;
}

/** Upcard order for every row below: 2 3 4 5 6 7 8 9 10 A. */
export const UPCARD_ORDER = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'A'] as const;

const row = (s: string): string[] => s.trim().split(/\s+/);

/** 6 decks, dealer hits soft 17, double any two, DAS, late surrender. */
export const SIX_DECK_H17_DAS_LS: PublishedChart = {
  name: '6 decks, H17, DAS, late surrender',
  hard: {
    5: row('H H H H H H H H H H'),
    6: row('H H H H H H H H H H'),
    7: row('H H H H H H H H H H'),
    8: row('H H H H H H H H H H'),
    9: row('H D D D D H H H H H'),
    10: row('D D D D D D D D H H'),
    11: row('D D D D D D D D D D'),
    12: row('H H S S S H H H H H'),
    13: row('S S S S S H H H H H'),
    14: row('S S S S S H H H H H'),
    15: row('S S S S S H H H R R'),
    16: row('S S S S S H H R R R'),
    17: row('S S S S S S S S S R'),
  },
  soft: {
    13: row('H H H D D H H H H H'),
    14: row('H H H D D H H H H H'),
    15: row('H H D D D H H H H H'),
    16: row('H H D D D H H H H H'),
    17: row('H D D D D H H H H H'),
    18: row('D D D D D S S H H H'),
    19: row('S S S S D S S S S S'),
    20: row('S S S S S S S S S S'),
  },
  pairs: {
    'A,A': row('P P P P P P P P P P'),
    '2,2': row('P P P P P P H H H H'),
    '3,3': row('P P P P P P H H H H'),
    '4,4': row('H H H P P H H H H H'),
    '5,5': row('D D D D D D D D H H'),
    '6,6': row('P P P P P H H H H H'),
    '7,7': row('P P P P P P H H H H'),
    '8,8': row('P P P P P P P P P R'),
    '9,9': row('P P P P P S P P S S'),
    'T,T': row('S S S S S S S S S S'),
  },
};

/** 6 decks, dealer stands on soft 17, double any two, DAS, late surrender. */
export const SIX_DECK_S17_DAS_LS: PublishedChart = {
  name: '6 decks, S17, DAS, late surrender',
  hard: {
    5: row('H H H H H H H H H H'),
    6: row('H H H H H H H H H H'),
    7: row('H H H H H H H H H H'),
    8: row('H H H H H H H H H H'),
    9: row('H D D D D H H H H H'),
    10: row('D D D D D D D D H H'),
    11: row('D D D D D D D D D H'),
    12: row('H H S S S H H H H H'),
    13: row('S S S S S H H H H H'),
    14: row('S S S S S H H H H H'),
    15: row('S S S S S H H H R H'),
    16: row('S S S S S H H R R R'),
    17: row('S S S S S S S S S S'),
  },
  soft: {
    13: row('H H H D D H H H H H'),
    14: row('H H H D D H H H H H'),
    15: row('H H D D D H H H H H'),
    16: row('H H D D D H H H H H'),
    17: row('H D D D D H H H H H'),
    18: row('S D D D D S S H H H'),
    19: row('S S S S S S S S S S'),
    20: row('S S S S S S S S S S'),
  },
  pairs: {
    'A,A': row('P P P P P P P P P P'),
    '2,2': row('P P P P P P H H H H'),
    '3,3': row('P P P P P P H H H H'),
    '4,4': row('H H H P P H H H H H'),
    '5,5': row('D D D D D D D D H H'),
    '6,6': row('P P P P P H H H H H'),
    '7,7': row('P P P P P P H H H H'),
    '8,8': row('P P P P P P P P P P'),
    '9,9': row('P P P P P S P P S S'),
    'T,T': row('S S S S S S S S S S'),
  },
};

/**
 * Cells where published sources legitimately disagree, usually because the two
 * actions are within a rounding error of each other. The spec is explicit that
 * these are documented as known-marginal rather than silently overridden
 * (§14.2), so the chart test reports them instead of failing on them.
 *
 * Keyed by scenario key. Empty until a real disagreement is found during the
 * §14.2 review; the mechanism is here so that resolving one is a data change.
 */
export const KNOWN_MARGINAL: ReadonlyMap<string, string> = new Map<string, string>();

/**
 * Rule-set deviations that are individually famous, asserted on their own rather
 * than as whole grids. Each is a discrete, well-attested consequence of one rule
 * changing, which makes it a sharp test of whether the engine really computes
 * from the rules rather than reciting a chart.
 */
export const NAMED_DEVIATIONS = [
  {
    preset: 'european-nhc',
    why: 'With no hole card a dealer natural also takes the split wager, so 8,8 stops being a split against a ten.',
    scenarioKey: 'bj:pair8:vs10',
    expect: 'hit',
  },
  {
    preset: 'european-nhc',
    why: 'Same reason, against an ace: splitting aces into a live dealer natural loses two units, not one.',
    scenarioKey: 'bj:pairA:vsA',
    expect: 'hit',
  },
  {
    preset: 'european-nhc',
    why: 'Doubling 11 against a ten risks the doubled wager to a dealer natural that has not been peeked for.',
    scenarioKey: 'bj:hard11:vs10',
    expect: 'hit',
  },
  {
    preset: 'single-deck-6-5',
    why: 'The single-deck 7,7-versus-ten exception: the player holds two of the four sevens, which guts the draw to 21.',
    scenarioKey: 'bj:pair7:vs10',
    expect: 'stand',
  },
] as const;
