-- 004 — the shared table
--
-- Run once, in the Supabase SQL editor, after 003. Paste the whole file and
-- press Run. It takes a moment.
--
-- Why: two or more people playing one shoe, each with his own cards, each
-- choosing for himself. What is stored is a seed, the rules, and what each
-- player did — never a card. Every card either player sees is worked out from
-- those by the app, which is what lets two phones show the same table without a
-- server that deals.
--
-- NOTHING IS DELETED AND NOTHING EXISTING IS TOUCHED. Two new tables are added.
-- `public.players` is not read, not written and not altered by this file: no
-- rating, no name, no saved session and no leaderboard row changes.
--
-- Safe before or after the app update:
--   - The app from before round 21 does not know these tables and never asks
--     for them, so it keeps working exactly as it does now.
--   - The new app, meeting a database without them, will say the shared table
--     is not ready rather than failing anywhere else.

-- ------------------------------------------------------------------ tables ---
--
-- One row a table. `seed` fixes the order of the shoe, and that is very nearly
-- all it holds: who is sitting, and what each of them did, lives one row per
-- seat in `table_seats`, so that nothing here is ever written by two people.
-- Every event carries the hand it happened at rather than a time, so the cards
-- can never depend on when anybody's phone happened to write.

create table if not exists public.tables (
  -- What the invitation link carries.
  id            text primary key,
  -- The shuffle. Generated by the app, never chosen by a player: a seed you can
  -- ask for is a shoe you can practise against twice.
  seed          integer     not null,
  -- The rule set the table deals under. Every seat plays these, not its own.
  preset_id     text        not null,
  restrictions  jsonb       not null default '{}'::jsonb,
  -- open · playing · complete · closed
  state         text        not null default 'open',
  seats         integer     not null default 2 check (seats between 2 and 6),
  created_by    text        not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ------------------------------------------------------------- table_seats ---
--
-- One row a seat, and **only that seat's player ever writes it**. That is the
-- whole concurrency design: there are no transactions here, and a row written
-- by one person can never lose another person's writes if nobody else writes
-- that row. It is also why the moves live here rather than in a column on
-- `tables`.

create table if not exists public.table_seats (
  table_id    text    not null references public.tables (id),
  -- 0 is the seat of whoever made the table.
  seat        integer not null check (seat >= 0 and seat < 6),
  -- Null until somebody sits down. The join writes it, and only while it is
  -- null — which is what makes two people pressing at once safe.
  player_id   text,
  name        text,
  -- Chips a unit for this seat. Each player bets what he likes.
  bet         numeric not null default 1 check (bet > 0),
  -- What this seat did, in order: {hand, round, action}. The cards follow.
  moves       jsonb   not null default '[]'::jsonb,
  -- How many hands this seat has been dealt. The moves alone cannot say: a hand
  -- where the dealer turns a natural is dealt, lost, and decided by nobody, so
  -- it leaves no move behind. Without this, a table whose last hand was one of
  -- those would replay one hand short on the other player's phone.
  hands       integer not null default 0,
  -- Reactions this seat sent, by hand. A fixed set; never free text.
  reactions   jsonb   not null default '{}'::jsonb,
  -- This seat's own vote to drop whoever is holding the table: {hand, against,
  -- at, needs}. A tally is naturally one shared number, and a shared number
  -- would be the one place two people write the same row — so each player
  -- records his own vote here and anybody can count them. `needs` is how many
  -- agreements that attempt required, read off the same table everybody else
  -- can see, so a drop can be worked out from the votes alone.
  vote        jsonb,
  -- What happened to THIS seat: it joined, it left, it came back. One row's
  -- events are written by one player, which is the whole concurrency design.
  -- These used to live in a single list on `tables`, where two people leaving
  -- at the same moment cost one of the events; there is no shared list now.
  events      jsonb   not null default '[]'::jsonb,
  -- This seat's hash of every card it was dealt. If two seats disagree, the
  -- app refuses to show the table rather than showing two different truths.
  cards_hash  text,
  -- Set once this seat's decisions have been taken into its owner's rating, so
  -- one seed can never be scored twice.
  rated       boolean not null default false,
  -- Last heartbeat. Written by this seat, read by the others to tell "thinking"
  -- from "gone". Nothing about the cards depends on it.
  seen_at     timestamptz,
  primary key (table_id, seat)
);

-- ------------------------------------------------------------------ index ---
--
-- The two questions the app asks: "which tables am I at" and "give me this
-- table's seats in order". The primary key answers the second.

create index if not exists table_seats_by_player
  on public.table_seats (player_id)
  where player_id is not null;

create index if not exists tables_by_creator on public.tables (created_by);

-- -------------------------------------------------------------------- rls ---
--
-- The same posture as `players`, and for the same reason: there are no
-- accounts, so anyone who can open the page can read the tables and write a
-- row. For a family sharing a link that is the right trade, and nothing private
-- is here — a name somebody chose and some blackjack.
--
-- DELETE is withheld deliberately. There is no policy for it, so it is refused:
-- the worst anyone can do is add a table or overwrite a seat, and no table's
-- history can be destroyed.

alter table public.tables enable row level security;
alter table public.table_seats enable row level security;

drop policy if exists "anyone may read tables" on public.tables;
create policy "anyone may read tables"
  on public.tables for select
  to anon, authenticated
  using (true);

drop policy if exists "anyone may open a table" on public.tables;
create policy "anyone may open a table"
  on public.tables for insert
  to anon, authenticated
  with check (true);

drop policy if exists "anyone may update a table" on public.tables;
create policy "anyone may update a table"
  on public.tables for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "anyone may read seats" on public.table_seats;
create policy "anyone may read seats"
  on public.table_seats for select
  to anon, authenticated
  using (true);

drop policy if exists "anyone may add seats" on public.table_seats;
create policy "anyone may add seats"
  on public.table_seats for insert
  to anon, authenticated
  with check (true);

drop policy if exists "anyone may update a seat" on public.table_seats;
create policy "anyone may update a seat"
  on public.table_seats for update
  to anon, authenticated
  using (true)
  with check (true);

-- ------------------------------------------------------------------ check ---
-- Run this afterwards:
--
--   select
--     (select count(*) from public.players)      as players_unchanged,
--     (select count(*) from public.tables)       as tables,
--     (select count(*) from public.table_seats)  as seats;
--
-- `players_unchanged` must be the same number it was before you ran this file —
-- 12, unless somebody has joined since — and `tables` and `seats` are both 0,
-- because nobody has made a table yet. The first one you make turns them into
-- 1 and 2.
